#
# -------------------------------------------------------------------------------
# © 2023 RedVelvet All Rights Reserved
# -------------------------------------------------------------------------------
#
# Author : <re@redvelvet.me> (https://redvelvet.me)
# GitHub : https://github.com/redvelvetme
# GitLab : https://gitlab.com/redvelvetme
#
#

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    ServerlessAPI [NodeJS-18.x Serverless Application Model]

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Runtime: nodejs18.x
        MemorySize: 256
        Timeout: 32

Resources:
    Index:
        # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: api/
            Handler: index.lambda_handler
            Runtime: nodejs18.x
            Architectures:
                - x86_64
            MemorySize: 128
            Timeout: 3
            Description: Exposed root endpoint returns only the health state of the application
            Events:
                Index:
                    # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Type: Api
                    Properties:
                        Path: /v0
                        Method: GET

    ApplicationResourceGroup:
        Type: AWS::ResourceGroups::Group
        Properties:
            Name:
                Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
            ResourceQuery:
                Type: CLOUDFORMATION_STACK_1_0
    ApplicationInsightsMonitoring:
        Type: AWS::ApplicationInsights::Application
        Properties:
            ResourceGroupName:
                Ref: ApplicationResourceGroup
            AutoConfigurationEnabled: 'true'
Outputs:
    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    IndexEndpoint:
        Description: 'API Gateway endpoint URL for `Prod` stage for Serverless API function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/v0'
    Index:
        Description: 'Index Lambda Function ARN'
        Value: !GetAtt Index.Arn
    IndexIamRole:
        Description: 'Implicit IAM Role created for index function'
        Value: !GetAtt IndexRole.Arn
